---
- name: "AFTER | Dropping an Audit/Scan Policy"
  ansible.builtin.import_tasks: audit_policy_drop.yml
  when: ora19cis_oracle_audit_policy_drop_afterwards
  run_once: true
  tags:
      - audit_policy_drop
