---
- name: "AFTER | Dropping an Audit/Scan Policy"
  vars:
      task_name: "Dropping an Audit/Scan Policy"
      sql_get: |
          {{ ora19cis_sqlplus_header_data_get }}
          SELECT POLICY_NAME FROM AUDIT_UNIFIED_POLICIES WHERE POLICY_NAME = '{{ ora19cis_oracle_audit_policy_name }}';
      sql_fix: |
          {{ ora19cis_sqlplus_header_data_fix }}
          NOAUDIT POLICY {{ ora19cis_oracle_audit_policy_name }};
          DROP AUDIT POLICY {{ ora19cis_oracle_audit_policy_name }};

  block:
      - name: "GET | {{ task_name }}"
        become_user: "{{ ora19cis_oracle_user }}"
        ansible.builtin.shell: echo "{{ sql_get }}" | {{ ora19cis_sqlplus_cmd }}
        environment: "{{ ora19cis_oracle_env | combine }}"
        register: result_get
        failed_when: result_get.stderr or result_get.rc != 0 or result_get.stdout | regex_search(ora19cis_sqlplus_failure_check_regex)
        changed_when: false

      - name: "FIX | {{ task_name }}"
        become_user: "{{ ora19cis_oracle_user }}"
        ansible.builtin.shell: echo "{{ sql_fix }}" | {{ ora19cis_sqlplus_cmd }}
        environment: "{{ ora19cis_oracle_env | combine }}"
        register: result_fix
        failed_when: result_fix.stderr or result_fix.rc != 0 or result_fix.stdout | regex_search(ora19cis_sqlplus_failure_check_regex)
        when: result_get.stdout

  tags:
      - audit_policy_drop
