---
- name: "PRELIM | Establishing an Audit/Scan User"
  vars:
      task_name: "Establishing an Audit/Scan User"
      sql_get: |
          SET HEADING OFF
          SET MARKUP CSV ON QUOTE OFF
          SELECT role FROM dba_roles WHERE role = '{{ ora19cis_oracle_audit_role_name }}';
      sql_fix: |
          CREATE ROLE {{ ora19cis_oracle_audit_role_name }}; 

  block:
      - name: "GET | {{ task_name }}"
        become_user: "{{ ora19cis_oracle_user }}"
        ansible.builtin.shell: echo "{{ sql_get }}" | {{ ora19cis_sqlplus_cmd }}
        environment: "{{ ora19cis_oracle_env | combine }}"
        register: result_get
        failed_when: result_get.stderr or result_get.rc != 0 or result_get.stdout | regex_search(ora19cis_sqlplus_failure_check_regex)
        changed_when: false

      - name: "FIX | {{ task_name }}"
        become_user: "{{ ora19cis_oracle_user }}"
        ansible.builtin.shell: echo "{{ sql_fix }}" | {{ ora19cis_sqlplus_cmd }}
        environment: "{{ ora19cis_oracle_env | combine }}"
        register: result_fix
        failed_when: result_fix.stderr or result_fix.rc != 0 or result_fix.stdout | regex_search(ora19cis_sqlplus_failure_check_regex)
        when: result_get.stdout | regex_search('no rows selected')

  tags:
      - audit_user_create
