---
- name: Preliminary Tasks
  ansible.builtin.import_tasks: prelim.yml

- name: Run CIS Section 2 Tasks
  ansible.builtin.import_tasks: section_2/main.yml
  when:
      - ora19cis_section_2
  tags:
      - ora19cis_section_2

- name: Run CIS Section 3 Tasks
  ansible.builtin.import_tasks: section_3/main.yml
  when:
      - ora19cis_section_3
  tags:
      - ora19cis_section_3

- name: Run CIS Section 4 Tasks
  ansible.builtin.import_tasks: section_4/main.yml
  when:
      - ora19cis_section_4
  tags:
      - ora19cis_section_4

- name: Run CIS Section 5 Tasks
  ansible.builtin.import_tasks: section_5/main.yml
  when:
      - ora19cis_section_5
  tags:
      - ora19cis_section_5

- name: Run CIS Section 6 Tasks
  ansible.builtin.import_tasks: section_6/main.yml
  when:
      - ora19cis_section_6
  tags:
      - ora19cis_section_6

- name: Post-Execution Tasks
  ansible.builtin.import_tasks: after.yml

- name: Output count and control IDs affected if any warnings have been detected during execution
  ansible.builtin.debug:
      msg: "You have {{ warn_count }} warning(s) that require attention and are related to the following benchmark ID(s)"
  when: warn_count != 0
  tags: always

- name: Output warnings
  ansible.builtin.debug:
      msg: "{{ warn_control_list }}"
  when: warn_count != 0
  tags: always

