---
- name: "PRELIM | Check database type we are connected to"
  ansible.builtin.import_tasks: audit_db_type.yml
  run_once: true
  tags:
      - audit_db_type

- name: "PRELIM | Check database unified auditing status"
  ansible.builtin.import_tasks: audit_unified_status.yml
  run_once: true
  tags:
      - audit_unified_status

