---
- name: "Run Section & Tasks"
  ansible.builtin.include_tasks: "{{ 'cis_' + item.task_tag + '.yml' }}"
  with_items:
    - { task_id: '6.1.1', task_tag: "6_1_1", task_name: "Ensure the 'USER' Audit Option Is Enabled" }
    - { task_id: '6.1.2', task_tag: "6_1_2", task_name: "Ensure the 'ROLE' Audit Option Is Enabled" }
    - { task_id: '6.1.3', task_tag: "6_1_3", task_name: "Ensure the 'SYSTEM GRANT' Audit Option Is Enabled" }
    - { task_id: '6.1.4', task_tag: "6_1_4", task_name: "Ensure the 'PROFILE' Audit Option Is Enabled" }
    - { task_id: '6.1.5', task_tag: "6_1_5", task_name: "Ensure the 'DATABASE LINK' Audit Option Is Enabled" }
    - { task_id: '6.1.6', task_tag: "6_1_6", task_name: "Ensure the 'PUBLIC DATABASE LINK' Audit Option Is Enabled" }
    - { task_id: '6.1.7', task_tag: "6_1_7", task_name: "Ensure the 'PUBLIC SYNONYM' Audit Option Is Enabled" }
    - { task_id: '6.1.8', task_tag: "6_1_8", task_name: "Ensure the 'SYNONYM' Audit Option Is Enabled" }
    - { task_id: '6.1.9', task_tag: "6_1_9", task_name: "Ensure the 'DIRECTORY' Audit Option Is Enabled" }
    - { task_id: '6.1.10', task_tag: "6_1_10", task_name: "Ensure the 'SELECT ANY DICTIONARY' Audit Option Is Enabled" }
    - { task_id: '6.1.11', task_tag: "6_1_11", task_name: "Ensure the 'GRANT ANY OBJECT PRIVILEGE' Audit Option Is Enabled" }
    - { task_id: '6.1.12', task_tag: "6_1_12", task_name: "Ensure the 'GRANT ANY PRIVILEGE' Audit Option Is Enabled" }
    - { task_id: '6.1.13', task_tag: "6_1_13", task_name: "Ensure the 'DROP ANY PROCEDURE' Audit Option Is Enabled" }
    - { task_id: '6.1.14', task_tag: "6_1_14", task_name: "Ensure the 'ALL' Audit Option on 'SYS.AUD$' Is Enabled" }
    - { task_id: '6.1.15', task_tag: "6_1_15", task_name: "Ensure the 'PROCEDURE' Audit Option Is Enabled" }
    - { task_id: '6.1.16', task_tag: "6_1_16", task_name: "Ensure the 'ALTER SYSTEM' Audit Option Is Enabled" }
    - { task_id: '6.1.17', task_tag: "6_1_17", task_name: "Ensure the 'TRIGGER' Audit Option Is Enabled" }
    - { task_id: '6.1.18', task_tag: "6_1_18", task_name: "Ensure the 'CREATE SESSION' Audit Option Is Enabled" }
    - { task_id: '6.2.1', task_tag: "6_2_1", task_name: "Ensure the 'CREATE USER' Action Audit Is Enabled" }
    - { task_id: '6.2.2', task_tag: "6_2_2", task_name: "Ensure the 'ALTER USER' Action Audit Is Enabled" }
    - { task_id: '6.2.3', task_tag: "6_2_3", task_name: "Ensure the 'DROP USER' Audit Option Is Enabled" }
    - { task_id: '6.2.4', task_tag: "6_2_4", task_name: "Ensure the 'CREATE ROLE' Action Audit Is Enabled" }
    - { task_id: '6.2.5', task_tag: "6_2_5", task_name: "Ensure the 'ALTER ROLE' Action Audit Is Enabled" }
    - { task_id: '6.2.6', task_tag: "6_2_6", task_name: "Ensure the 'DROP ROLE' Action Audit Is Enabled" }
    - { task_id: '6.2.7', task_tag: "6_2_7", task_name: "Ensure the 'GRANT' Action Audit Is Enabled" }
    - { task_id: '6.2.8', task_tag: "6_2_8", task_name: "Ensure the 'REVOKE' Action Audit Is Enabled" }
    - { task_id: '6.2.9', task_tag: "6_2_9", task_name: "Ensure the 'CREATE PROFILE' Action Audit Is Enabled" }
    - { task_id: '6.2.10', task_tag: "6_2_10", task_name: "Ensure the 'ALTER PROFILE' Action Audit Is Enabled" }
    - { task_id: '6.2.11', task_tag: "6_2_11", task_name: "Ensure the 'DROP PROFILE' Action Audit Is Enabled" }
    - { task_id: '6.2.12', task_tag: "6_2_12", task_name: "Ensure the 'CREATE DATABASE LINK' Action Audit Is Enabled" }
    #- { task_id: '6.2.', task_tag: "6_2_", task_name: "" }
  tags: always
