---

- name: "{{ 'TASK | ' + item.task_id + ' ' + item.task_name }}"
  vars:
      task_name: "{{ item.task_id + ' ' + item.task_name }}"
      sql_get: |
          {{ ora19cis_sqlplus_header_data_get }}
          SELECT UPPER(VALUE) FROM V\$SYSTEM_PARAMETER WHERE UPPER(NAME)='REMOTE_LOGIN_PASSWORDFILE';
      sql_fix: |
          {{ ora19cis_sqlplus_header_data_fix }}
          ALTER SYSTEM SET REMOTE_LOGIN_PASSWORDFILE = 'NONE' SCOPE = SPFILE;

  block:
      - name: "GET | {{ task_name }}"
        become_user: "{{ ora19cis_oracle_user }}"
        ansible.builtin.shell: echo "{{ sql_get }}" | {{ ora19cis_sqlplus_cmd }} 
        environment: "{{ ora19cis_oracle_env | combine }}"
        register: result_get
        failed_when: result_get.stderr or result_get.rc != 0 or result_get.stdout | regex_search(ora19cis_sqlplus_failure_check_regex)
        changed_when: false
        tags: get

      - ansible.builtin.debug:
          msg: "{{ result_get }}"
        when: sqlplus_debug

      - name: "FIX | {{ task_name }}"
        become_user: "{{ ora19cis_oracle_user }}"
        ansible.builtin.shell: echo "{{ sql_fix }}" | {{ ora19cis_sqlplus_cmd }}
        environment: "{{ ora19cis_oracle_env | combine }}"
        register: result_fix
        failed_when: result_fix.stderr or result_fix.rc != 0 or result_fix.stdout | regex_search(ora19cis_sqlplus_failure_check_regex)
        when: result_get.stdout != 'NONE'
        notify: restart_db_instance

      - ansible.builtin.debug:
          msg: "{{ result_fix }}"
        when: sqlplus_debug

  when:
      - ora19cis_rules[item.task_tag]
      - not ora19cis_oracle_db_multitenant or not ora19cis_oracle_db_pluggable

  tags:
      - level_1
      - level_2
      - fix
      - "{{ 'rule_' + item.task_tag }}"
