---
# Section 2
# Oracle Parameter Settings

- name: "{{ 'TASK | ' + item.task_id + ' ' + item.task_name }}"
  ansible.builtin.lineinfile:
      path: "{{ ora19cis_oracle_listener_ora }}"
      regexp: '^ADMIN_RESTRICTIONS_{{loop_item}}\s*='
      line: "ADMIN_RESTRICTIONS_{{loop_item}} = ON"
      insertafter: EOF
  loop_control:
      loop_var: loop_item
  notify: restart_listeners
  with_items: "{{ ora19cis_oracle_listener_names }}"

  when:
      - ora19cis_rule_2_1_2
  tags:
      - fix
      - level_1
      - level_2
      - rule_2_1_2

