---
# Section 2
# Oracle Parameter Settings

- name: "FIX | 2.1.2 Ensure 'ADMIN_RESTRICTIONS_' Is Set to 'ON'"
  ansible.builtin.lineinfile:
    path: "{{ ora19cis_oracle_listener_ora }}"
    regexp: '^ADMIN_RESTRICTIONS_{{item}}\s*='
    line: "ADMIN_RESTRICTIONS_{{item}} = ON"
    insertafter: EOF
  notify: restart listeners
  with_items: "{{ ora19cis_oracle_listener_names }}"

  when:
      - ora19cis_rule_2_1_2
  tags:
      - fix
      - level_1
      - level_2
      - rule_2_1_2

