---
# Section 2
# Oracle Parameter Settings

- name: "{{ 'TASK | ' + item.task_id + ' ' + item.task_name }}"
  ansible.builtin.lineinfile:
      path: "{{ ora19cis_oracle_sqlnet_ora }}"
      regexp: '^(?i)sqlnet\.crypto_checksum_server\s*='
      line: "sqlnet.crypto_checksum_server = required"
      insertafter: EOF
  notify: restart_listeners

  when:
      - ora19cis_rules[item.task_tag]

  tags:
      - fix
      - level_1
      - level_2
      - "{{ 'rule_' + item.task_tag }}"
