---
- name: "Run Section 2 Tasks"
  ansible.builtin.include_tasks: "{{ 'cis_' + item.task_tag + '.yml' }}"
  with_items:
    - { task_id: '2.1.1', task_tag: "2_1_1", task_name: "Ensure 'extproc' Is Not Present in 'listener.ora'" }
    - { task_id: '2.1.2', task_tag: "2_1_2", task_name: "Ensure 'ADMIN_RESTRICTIONS_' Is Set to 'ON'" }
    - { task_id: '2.2.1', task_tag: "2_2_1", task_name: "Ensure 'AUDIT_SYS_OPERATIONS' Is Set to 'TRUE'"  }
