---

- name: "{{ 'TASK | ' + item.task_id + ' ' + item.task_name }}"
  vars:
      task_name: "{{ item.task_id + ' ' + item.task_name }}"
      sql_get: |
          {{ ora19cis_sqlplus_header_data_get }}
          SELECT USERNAME FROM DBA_USERS WHERE PROFILE='DEFAULT' AND ACCOUNT_STATUS='OPEN' AND ORACLE_MAINTAINED = 'N';
      sql_fix: |
          {{ ora19cis_sqlplus_header_data_fix }}
          ALTER USER %s PROFILE {{ ora19cis_oracle_user_profile_set }};

  block:
      - name: "GET | {{ task_name }}"
        become_user: "{{ ora19cis_oracle_user }}"
        ansible.builtin.shell: echo "{{ sql_get }}" | {{ ora19cis_sqlplus_cmd }} 
        environment: "{{ ora19cis_oracle_env | combine }}"
        register: result_get 
        failed_when: result_get.stderr or result_get.rc != 0 or result_get.stdout | regex_search(ora19cis_sqlplus_failure_check_regex)
        changed_when: false
        tags: get

      - ansible.builtin.debug:
          msg: "{{ result_get }}"
        when: sqlplus_debug

      - name: "WARN | {{ task_name }}"
        ansible.builtin.import_tasks: collect_cis_warnings.yml
        vars:
            warn_control_id: "{{ item.task_id }}"
            warn_control_msg: "Warning! These database have DEFAULT profile set {{ result_get.stdout_lines }}. Please assign news profile value to the variable ora19cis_oracle_user_profile_set in defaults/main.yaml in order to set profile automatically"
        when: not ora19cis_oracle_user_profile_set and result_get.stdout
        tags: get

      - name: "FIX | {{ task_name }}"
        become_user: "{{ ora19cis_oracle_user }}"
        ansible.builtin.shell: echo "{{ sql_fix | regex_replace('%s', item_get) }}" | {{ ora19cis_sqlplus_cmd }}
        with_items: "{{ result_get.stdout_lines }}"
        loop_control:
           loop_var: item_get
        environment: "{{ ora19cis_oracle_env | combine }}"
        register: result_fix
        failed_when: result_fix.stderr or result_fix.rc != 0 or result_fix.stdout | regex_search(ora19cis_sqlplus_failure_check_regex)
        when: ora19cis_oracle_user_profile_set and result_get.stdout

      - ansible.builtin.debug:
          msg: "{{ result_fix }}"
        when: sqlplus_debug

      - name: "WARN | {{ task_name }}"
        ansible.builtin.import_tasks: collect_cis_warnings.yml
        vars:
            warn_control_id: "{{ item.task_id }}"
            warn_control_msg: "Warning! These database users used to have DEFAULT profile set {{ result_get.stdout_lines }}. They have been assigned this profile: '{{ ora19cis_oracle_user_profile_set }}'"
        when: ora19cis_oracle_user_profile_set and result_get.stdout


  when:
      - ora19cis_rules[item.task_tag]

  tags:
      - level_1
      - level_2
      - fix
      - "{{ 'rule_' + item.task_tag }}"
