---

- name: "{{ 'TASK | ' + item.task_id + ' ' + item.task_name }}"
  vars:
      task_name: "{{ item.task_id + ' ' + item.task_name }}"
      sql_get: |
          {{ ora19cis_sqlplus_header_data_get }}
          SET HEADING OFF
          SET FEEDBACK OFF
          SET MARKUP CSV ON QUOTE OFF
          SELECT USERNAME FROM DBA_USERS WHERE AUTHENTICATION_TYPE = 'EXTERNAL';
      sql_fix: |
          {{ ora19cis_sqlplus_header_data_fix }}
          ALTER USER %s IDENTIFIED BY "{{ ora19cis_oracle_user_password_new }}";

  block:
      - name: "GET | {{ task_name }}"
        become_user: "{{ ora19cis_oracle_user }}"
        ansible.builtin.shell: echo "{{ sql_get }}" | {{ ora19cis_sqlplus_cmd }} 
        environment: "{{ ora19cis_oracle_env | combine }}"
        register: result_get
        failed_when: result_get.stderr or result_get.rc != 0 or result_get.stdout | regex_search(ora19cis_sqlplus_failure_check_regex)
        changed_when: false
        tags: get

      - name: "FIX | {{ task_name }}"
        become_user: "{{ ora19cis_oracle_user }}"
        ansible.builtin.shell: echo "{{ sql_fix | regex_replace('%s', item_get) }}" | {{ ora19cis_sqlplus_cmd }}
        with_items: "{{ result_get.stdout_lines }}"
        loop_control:
           loop_var: item_get
        environment: "{{ ora19cis_oracle_env | combine }}"
        register: result_fix
        failed_when: result_fix.stderr or result_fix.rc != 0 or result_fix.stdout | regex_search(ora19cis_sqlplus_failure_check_regex)
        when: result_get.stdout

      - name: "WARN | {{ task_name }}"
        ansible.builtin.import_tasks: collect_cis_warnings.yml
        vars:
            warn_control_id: "{{ item.task_id }}"
            warn_control_msg: "Warning! These database users used to have external authentication set {{ result_get.stdout_lines }}. They have been assigned this NEW password: '{{ ora19cis_oracle_user_password_new }}'"
        when: result_get.stdout

  when:
      - ora19cis_rules[item.task_tag]

  tags:
      - level_1
      - level_2
      - fix
      - "{{ 'rule_' + item.task_tag }}"
