---

- name: "{{ 'TASK | ' + item.task_id + ' ' + item.task_name }}"
  vars:
      task_name: "{{ item.task_id + ' ' + item.task_name }}"
      sql_get: |
          {{ ora19cis_sqlplus_header_data_get }}
          SELECT DISTINCT A.USERNAME FROM DBA_USERS_WITH_DEFPWD A, DBA_USERS B WHERE A.USERNAME = B.USERNAME AND B.ACCOUNT_STATUS = 'OPEN';
  block:
      - name: "GET | {{ task_name }}"
        become_user: "{{ ora19cis_oracle_user }}"
        ansible.builtin.shell: echo "{{ sql_get }}" | {{ ora19cis_sqlplus_cmd }} 
        environment: "{{ ora19cis_oracle_env | combine }}"
        register: result_get
        failed_when: result_get.stderr or result_get.rc != 0 or result_get.stdout | regex_search(ora19cis_sqlplus_failure_check_regex)
        changed_when: false

      - name: "FIX | {{ task_name }}"
        ansible.builtin.debug:
            msg:
                - "Warning!! These database users have default passwords set. Please change them: {{ result_get.stdout_lines }}"
        when: result_get.stdout

      - name: "FIX | {{ task_name }}"
        ansible.builtin.import_tasks: collect_cis_warnings.yml
        vars:
            warn_control_id: "{{ item.task_id }}"
        when: result_get.stdout

  when:
      - ora19cis_rules[item.task_tag]

  tags:
      - level_1
      - level_2
      - get
      - fix
      - "{{ 'rule_' + item.task_tag }}"
