---

- name: "{{ 'TASK | ' + item.task_id + ' ' + item.task_name }}"
  vars:
      task_name: "{{ item.task_id + ' ' + item.task_name }}"
      sql_get: |
          SET HEADING OFF
          SET MARKUP CSV ON QUOTE OFF
          -- SELECT DISTINCT A.USERNAME FROM DBA_USERS_WITH_DEFPWD A, DBA_USERS B WHERE A.USERNAME = B.USERNAME AND B.ACCOUNT_STATUS = 'OPEN';
          SELECT DISTINCT A.USERNAME FROM DBA_USERS A;
  block:
      - name: "GET | {{ task_name }}"
        become_user: "{{ ora19cis_oracle_user }}"
        ansible.builtin.shell: echo "{{ sql_get }}" | {{ ora19cis_sqlplus_cmd }} 
        environment: "{{ ora19cis_oracle_env | combine }}"
        register: result_get
        failed_when: result_get.stderr or result_get.rc != 0 or result_get.stdout | regex_search(ora19cis_sqlplus_failure_check_regex)
        changed_when: false

      - name: "FIX | {{ task_name }}"
        ansible.builtin.debug:
            msg:
                - "Warning!! These database users have default passwords set. Please change them:"
                - "PASSWORD_VERIFY_FUNCTION is NOT set for profile: {{ item_get }}"
        with_items: "{{ result_get.stdout_lines }}"
        loop_control:
           loop_var: item_get
        when: not result_get.stdout | regex_search('no rows selected')

      - name: "FIX | {{ task_name }}"
        ansible.builtin.import_tasks: collect_cis_warnings.yml
        vars:
            warn_control_id: "{{ item.task_id }}"
        when: not result_get.stdout | regex_search('no rows selected')

  when:
      - ora19cis_rules[item.task_tag]

  tags:
      - level_1
      - level_2
      - get
      - fix
      - "{{ 'rule_' + item.task_tag }}"
